=== russtolyar/solved-hw-012-git/src/main/resources/house.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

	<xsd:element name="house">
		<xsd:complexType>
			<xsd:sequence>

				<xsd:element name="stage">
					<xsd:complexType>
						<xsd:sequence>

							<xsd:element name="flats">
								<xsd:complexType>
									<xsd:sequence>

										<xsd:element name="flat" maxOccurs="100" minOccurs="0">
											<xsd:complexType>
												<xsd:sequence>

													<xsd:element name="rooms">
														<xsd:complexType>
															<xsd:sequence>

																<xsd:element name="room" maxOccurs="10" minOccurs="0">
																	<xsd:complexType>
																		<xsd:sequence>

																			<xsd:element name="wall">
																				<xsd:complexType>
																					<xsd:sequence>

																						<xsd:element
																								name="materialWall">
																							<xsd:simpleType>
																								<xsd:restriction
																										base="xsd:string">
																									<xsd:enumeration
																											value="WOOD"/>
																									<xsd:enumeration
																											value="BRICK"/>
																									<xsd:enumeration
																											value="BETON"/>
																									<xsd:enumeration
																											value="STEEL"/>
																								</xsd:restriction>
																							</xsd:simpleType>
																						</xsd:element>

																					</xsd:sequence>
																				</xsd:complexType>
																			</xsd:element>

																			<xsd:element name="roomType">
																				<xsd:simpleType>
																					<xsd:restriction base="xsd:string">
																						<xsd:enumeration
																								value="DINNING"/>
																						<xsd:enumeration
																								value="LIVING"/>
																						<xsd:enumeration
																								value="STUDIO"/>
																						<xsd:enumeration
																								value="BEDROOM"/>
																						<xsd:enumeration
																								value="KITCHEN"/>
																						<xsd:enumeration
																								value="SEMISTUDIO"/>
																					</xsd:restriction>
																				</xsd:simpleType>
																			</xsd:element>

																			<xsd:element name="ceiling">
																				<xsd:complexType mixed="true">
																					<xsd:sequence>

																						<xsd:element
																								name="colorCeiling">
																							<xsd:simpleType>
																								<xsd:restriction
																										base="xsd:string">
																									<xsd:enumeration
																											value="WHITE"/>
																									<xsd:enumeration
																											value="PINK"/>
																									<xsd:enumeration
																											value="ORANGE"/>
																									<xsd:enumeration
																											value="BLUE"/>
																								</xsd:restriction>
																							</xsd:simpleType>
																						</xsd:element>
																					</xsd:sequence>
																				</xsd:complexType>
																			</xsd:element>

																		</xsd:sequence>
																		<xsd:attribute type="xsd:string" name="name"
																		               use="optional"/>
																	</xsd:complexType>
																</xsd:element>

															</xsd:sequence>
															<xsd:attribute type="xsd:string" name="name"
															               use="optional"/>
														</xsd:complexType>
													</xsd:element>

												</xsd:sequence>
												<xsd:attribute type="xsd:int" name="number" use="optional"/>
											</xsd:complexType>
										</xsd:element>

									</xsd:sequence>
								</xsd:complexType>
							</xsd:element>

						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>

				<xsd:element name="countStage" type="xsd:int"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>


</xsd:schema>

=== russtolyar/solved-hw-012-git/src/main/resources/house.xml
<?xml version="1.0" encoding="UTF-8"?>
<house xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:noNamespaceSchemaLocation="house.xsd" >
    <stage>
        <flats>
            <flat number="1">
                <rooms name="dinning, Living">
                    <room name="dinning">
                        <wall>
                            <materialWall>WOOD</materialWall>
                        </wall>
                        <roomType>DINNING</roomType>
                        <ceiling>
                            <colorCeiling>WHITE</colorCeiling>
                        </ceiling>
                    </room>
                    <room name="living">
                        <wall>
                            <materialWall>BRICK</materialWall>
                        </wall>
                        <roomType>LIVING</roomType>
                        <ceiling>
                            <colorCeiling>PINK</colorCeiling>
                        </ceiling>
                    </room>
                </rooms>
            </flat>
            <flat number="2">
                <rooms name="studios">
                    <room name="studio">
                        <wall>
                            <materialWall>BETON</materialWall>
                        </wall>
                        <roomType>STUDIO</roomType>
                        <ceiling>
                            <colorCeiling>BLUE</colorCeiling>
                        </ceiling>
                    </room>
                    <room name="semistudio">
                        <wall>
                            <materialWall>STEEL</materialWall>
                        </wall>
                        <roomType>SEMISTUDIO</roomType>
                        <ceiling>
                            <colorCeiling>ORANGE</colorCeiling>
                        </ceiling>
                    </room>
                </rooms>
            </flat>
        </flats>

    </stage>
    <countStage>1</countStage>

    </house>
